# Generated by Django 3.2 on 2022-09-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='стоимость, $')),
                ('price_rub', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='стоимость, руб')),
                ('delivery_term', models.DateField(verbose_name='срок поставки')),
            ],
            options={
                'verbose_name': 'поставка',
                'verbose_name_plural': 'поставки',
            },
        ),
    ]
