# Generated by Django 3.2 on 2022-09-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_term',
            field=models.DateField(default=None, null=True, verbose_name='срок поставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_rub',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='стоимость, руб'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='стоимость, $'),
        ),
    ]
